### ISSUE TITLE
Auditing for PowerAuth backends

### ISSUE THREAD

**Issue by romanstrobl** [wultra/lime-java-core#34]
Implement a solution for auditing in PowerAuth backends with following requirements.

1. Use the following fields for auditing:
  - timestamp
  - application
  - event type (informational, exception)
  - message (free text with logged message)
  - level of severity
  - user ID (optional)
  - operation ID (operation from audited component, optional)
  - external operation ID (operation from parent component, optional)
  - activation ID (only when PowerAuth is used, optional)
  - extras (additional details, optional)
  - stack trace (for exception, optional)

2. The auditing code should be reusable across multiple PowerAuth projects and it should be available as an optional dependency.

3. The auditing table name needs to be configurable to allow auditing from multiple projects into the same table.

4. Supported databases:
- MySQL
- Oracle
- PostgreSQL

5. Use spring properties for configuration of the library with reasonable defaults (e.g. auditing table name).

**Comment by petrdvorak** [comment]
Just a quick side note: I recommend doing a little generic research for this area first, so that we do not forget some data columns and avoid overengineering.

**Comment by romanstrobl** [comment]
Yes, I agree. I would start with a minimalistic solution for 2021.05. I think we should start with a small specification with minimal functionality for this release (one shared DB table) but a plan for extension in next release (e.g. elastic integration or other system integration). In next release we could consider adding some UI, too, e.g. find events for activation in PA admin.

**Comment by petrdvorak** [comment]
Yes. Also, one aspect I want to explore is if DB is the only place to store data to, or if Elastic or Splunk are options too...
